# -*- mode: makefile-gmake; coding:utf-8 -*-
#
#  Yet Another Teachable Operating System
#  Copyright 2016 Takeharu KATO
#
top=../..
include ${top}/Makefile.inc
CFLAGS += -I${top}/include
objects=

all: clean

clean:
	${RM} asm-offset.h

distclean:clean
	${RM} *~
