# -*- mode: makefile-gmake; coding:utf-8 -*-
#
#  Yet Another Teachable Operating System
#  Copyright 2016 Takeharu KATO
#
top=..
include ${top}/Makefile.inc
CFLAGS += -I${top}/include
objects=
lib=libXXXX.a

all:${lib}

${lib}: clean-lib ${objects}
	${RM} ${lib}
	${AR} ${ARFLAGS} $@ ${objects}
	${RANLIB} $@

clean:
	${RM} *.o ${lib}

distclean:clean
	${RM} *~

clean-lib:
	${RM} ${lib}
